# Generated by Django 2.2.5 on 2020-01-29 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BalRec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('recType', models.PositiveIntegerField()),
                ('disType', models.PositiveIntegerField()),
                ('income', models.FloatField()),
                ('outcome', models.FloatField()),
                ('detail', models.CharField(max_length=255)),
            ],
        ),
    ]
