# Generated by Django 2.2.5 on 2020-01-29 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recorder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balrec',
            old_name='date',
            new_name='datex',
        ),
    ]
