# Generated by Django 2.2.5 on 2020-01-29 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recorder', '0002_auto_20200129_0753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balrec',
            old_name='outcome',
            new_name='output',
        ),
    ]
