# Generated by Django 2.2.5 on 2020-02-03 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recorder', '0003_auto_20200129_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='balrec',
            name='abstract',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
